### ISSUE TITLE
Update `CONTRIBUTING.md` to reflect `v2.0.0` conventions

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/brainglobe-meta#1]
**Is your feature request related to a problem? Please describe.**
`CONTRIBUTING.md` should be updated with suitable content reflecting the fact that contributing to this repository (the meta-package) and contributing to a specific BrainGlobe tool (EG cellfinder) will be done in different repositories.

All comments & thoughts welcome in the discussion.

Other things for us to consider and update are:
- How do we introduce/point new developers to the appropriate repository for a particular tool, given that the meta-package purpose is to (somewhat) remove this distinction on the user-facing side.
- Do we want to delegate contribution guidelines to the underlying tool repositories, point to a central guide (EG in this repo), or repeat ourselves to be safe across multiple repositories?

**Describe the solution you'd like**
The above points to be answered and content in `CONTRIBUTING.md` updated accordingly.

**Describe alternatives you've considered**

**Additional context**

**Comment by adamltyson** [comment]
> Do we want to delegate contribution guidelines to the underlying tool repositories, point to a central guide (EG in this repo), or repeat ourselves to be safe across multiple repositories?

Maybe we could add all the developer information to a section on the new website (currently [here](https://github.com/brainglobe/new-website)), and then link to this from both `CONTRIBUTING.md` and a section of each repo's README?

**Comment by willGraham01** [comment]
> At some point soon that website will move to https://brainglobe.info/ FYI

No worries, I'll leave #3 as a draft for now, and merge it in after the website moves.

**Comment by adamltyson** [comment]
Website is now live at https://brainglobe.info/
