### ISSUE TITLE
[Feature] Ship `brainrender`

### ISSUE THREAD

**Issue by willGraham01** [brainglobe/brainglobe-meta#14]
**Is your feature request related to a problem? Please describe.**
[`brainrender`](https://github.com/brainglobe/brainrender) should be shipped as part of the meta-package.

**Describe the solution you'd like**
As above.

- Add brainrender to the list of pip dependencies.
- Add brainrender to conda-forge so the conda package can install it.

**Comment by adamltyson** [comment]
No rush on this. I think there's a bit of work to do to get brainrender up to date, and compatible with the dependencies of the other tools.

**Comment by willGraham01** [comment]
No problem - it also looks like `brainrender` depends on `morphio`, which is another thing on my `conda` to-do list.

Barring the Python 3.8 hard-dependencies though, we could ship this with the meta-package (via `pip`) as it is.

**Comment by adamltyson** [comment]
I think there are quite a few other dependency conflicts. Should be good once https://github.com/brainglobe/brainrender/pull/235 is merged.

**Comment by adamltyson** [comment]
brainrender should be good to go now I think.

**Comment by willGraham01** [comment]
> brainrender should be good to go now I think.

Will open up a PR for the PyPI package at least. We still depend on [morphapi (hence morphio)](https://github.com/brainglobe/brainrender/blob/3003fdae22a2a8f10721ba0244bb3b59adb7c576/pyproject.toml#L19C16-L19C16) so won't be available on conda
